variables:
  HOST: "ftpupload.net"
  USERNAME: "epiz_27915542"
  PASSWORD: "6imxAt2FdAx4j5"

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    - lftp -c "set ftp:ssl-allow no; open -u epiz_27915542E,6imxAt2FdAx4j5 ftpupload.net; mirror -Rnev ./ ./public_html --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"

only:
  - master
