deploy_all:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - git config git-ftp.url "ftpupload.net"
    - git config git-ftp.password "6imxAt2FdAx4j5"
    - git config git-ftp.user "epiz_27915542"
    - git ftp init
    #- git ftp push  -m "Add new content"

  only:
    - master
